// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
)

type Car struct {
	CarID        int32  `json:"car_id"`
	Make         string `json:"make"`
	Model        string `json:"model"`
	Price        string `json:"price"`
	Transmission string `json:"transmission"`
	TrimLevel    string `json:"trim_level"`
	Color        string `json:"color"`
}

type Owner struct {
	OwnerID     int32  `json:"owner_id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	PhoneNumber int32  `json:"phone_number"`
	Email       string `json:"email"`
}

type Sale struct {
	SaleID  int32         `json:"sale_id"`
	CarID   sql.NullInt32 `json:"car_id"`
	OwnerID sql.NullInt32 `json:"owner_id"`
}
