// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreateCar(ctx context.Context, arg CreateCarParams) (Car, error)
	CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	DeleteCar(ctx context.Context, carID int32) error
	DeleteOwner(ctx context.Context, ownerID int32) error
	DeleteSale(ctx context.Context, saleID int32) error
	GetAllCars(ctx context.Context) ([]Car, error)
	GetAllOwners(ctx context.Context) ([]Owner, error)
	GetAllSales(ctx context.Context) ([]Sale, error)
	GetCarDetails(ctx context.Context, carID int32) (Car, error)
	GetOwnerDetails(ctx context.Context, ownerID int32) (Owner, error)
	GetSaleDetails(ctx context.Context, saleID int32) (Sale, error)
	UpdateCar(ctx context.Context, arg UpdateCarParams) error
	UpdateOwner(ctx context.Context, arg UpdateOwnerParams) error
	UpdateSale(ctx context.Context, arg UpdateSaleParams) error
}

var _ Querier = (*Queries)(nil)
