// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Movie struct {
	MovieID     int32     `json:"movie_id"`
	Title       string    `json:"title"`
	Overview    string    `json:"overview"`
	ReleaseDate time.Time `json:"release_date"`
	PosterUrl   string    `json:"poster_url"`
}

type Rating struct {
	RatingID int32         `json:"rating_id"`
	MovieID  sql.NullInt32 `json:"movie_id"`
	UserID   sql.NullInt32 `json:"user_id"`
	Score    int32         `json:"score"`
}

type User struct {
	UserID   int32  `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
