// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
)

type Movie struct {
	MovieID     int32          `json:"movie_id"`
	Title       sql.NullString `json:"title"`
	Overview    sql.NullString `json:"overview"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	PosterUrl   sql.NullString `json:"poster_url"`
}

type Rating struct {
	RatingID int32         `json:"rating_id"`
	MovieID  sql.NullInt32 `json:"movie_id"`
	UserID   sql.NullInt32 `json:"user_id"`
	Score    sql.NullInt32 `json:"score"`
}

type User struct {
	UserID   int32          `json:"user_id"`
	Username sql.NullString `json:"username"`
	Password sql.NullString `json:"password"`
	Email    sql.NullString `json:"email"`
}
